apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    release: webapp
  name: nginx-deployment
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - env:
            - name: APP_COLOR
              value: yellow
          image: 'quay.io/opsmxpublic/simple-webapp:3'
          name: simple-webapp
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: webapp
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: webapp
  name: webapp-ingress
spec:
  rules:
    - host: bluegreendemo.isd.training.opsmx.net
      http:
        paths:
          - backend:
              service:
                 name: webapp
                 port:
                   number: 80
            path: /
            pathType: ImplementationSpecific
