apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    release: '${parameters.release}'
  name: 'webapp-deployment-${parameters.release}'
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: webapp
      release: '${parameters.release}'
  template:
    metadata:
      labels:
        app: webapp
        release: '${parameters.release}'
    spec:
      containers:
        - env:
            - name: APP_COLOR
              value: blue
          image: 'quay.io/opsmxpublic/simple-webapp:1'
          name: simple-webapp
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: '${parameters.service_name}'
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: nginx
    release: '${parameters.release}'
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: webapp
    release: '${parameters.release}'
  name: 'webapp-ingress-${parameters.release}'
spec:
  rules:
    - host: bluegreendemo.autopilot.opsmx.com
      http:
        paths:
          - backend:
              serviceName: '${parameters.service_name}'
              servicePort: 80
